export const DELETE_TRADES = 'DELETE_TRADES';
export const GET_TRADE = 'GET_TRADE';

export const GET_TRADES_REQUEST = 'GET_TRADES_REQUEST';
export const GET_TRADES_SUCCESS = 'GET_TRADES_SUCCESS';
export const GET_TRADES_ERROR = 'GET_TRADES_ERROR';

export const SET_TRADE_REQUEST = 'SET_TRADE_REQUEST';
export const SET_TRADE_SUCCESS = 'SET_TRADE_SUCCESS';
export const SET_TRADE_ERROR = 'SET_TRADE_ERROR';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const CHANGE_ACCOUNT = 'CHANGE_ACCOUNT ';

export const CHANGE_STATUS_ONREAD = 'CHANGE_STATUS_ONREAD';
